-- =====================================================================
-- Astute Work Tracker on Supabase: tables
-- Nothing here is reachable from the browser directly. Row level security is on for every
-- table with no policies, and all reads and writes go through app.api(), which checks
-- who is signed in and what they may see.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- Everything lives in the private "app" schema, which the Data API does not expose.
-- The only door in from the browser is public.api() (see 05_api.sql).
create schema if not exists app;
revoke all on schema app from public;

create table if not exists app.settings (
  key   text primary key,
  value text not null
);

create table if not exists app.companies (
  id             bigint generated by default as identity primary key,
  name           text not null,
  weekly_offs    text not null default '0',          -- comma list of weekdays, 0 = Sunday
  weight_small   int  not null default 1,
  weight_medium  int  not null default 2,
  weight_large   int  not null default 4,
  created_at     timestamptz not null default now()
);
create unique index if not exists companies_name_key on app.companies (lower(name));

create table if not exists app.holidays (
  id          bigint generated by default as identity primary key,
  company_id  bigint not null references app.companies(id) on delete cascade,
  date        date not null,
  name        text not null,
  unique (company_id, date)
);

create table if not exists app.users (
  id          bigint generated by default as identity primary key,
  auth_id     uuid unique,                              -- the Supabase Auth account, once linked
  name        text not null,
  email       text not null,
  role        text not null check (role in ('admin','workforce')),
  title       text,
  active      boolean not null default true,
  tutorial_done_at timestamptz,                         -- when they finished the first-login walkthrough
  created_at  timestamptz not null default now()
);
create unique index if not exists users_email_key on app.users (lower(email));
alter table app.users add column if not exists tutorial_done_at timestamptz;

create table if not exists app.projects (
  id                          bigint generated by default as identity primary key,
  company_id                  bigint not null references app.companies(id),
  name                        text not null,
  description                 text,
  status                      text not null default 'active' check (status in ('active','on_hold','completed','cancelled')),
  target_end_date             date,
  show_progress_to_workforce  boolean not null default true,
  auto_approve                boolean not null default false,
  progress_pct                double precision not null default 0,
  pending_pct                 double precision not null default 0,
  created_by                  bigint references app.users(id),
  created_at                  timestamptz not null default now()
);

-- Modules and features share one table: parent_id null = module.
create table if not exists app.work_items (
  id                 bigint generated by default as identity primary key,
  project_id         bigint not null references app.projects(id) on delete cascade,
  parent_id          bigint references app.work_items(id) on delete cascade,
  level              text not null check (level in ('module','feature')),
  name               text not null,
  description        text,
  size               text not null check (size in ('small','medium','large')),
  weight             int  not null,
  sequence           int  not null default 0,
  status             text not null default 'not_started'
                     check (status in ('proposed','not_started','in_progress','blocked','submitted','done','on_hold','cancelled')),
  status_reason      text,
  origin             text not null default 'admin' check (origin in ('admin','workforce')),
  proposed_by        bigint references app.users(id),
  proposal_reason    text,
  accepted_by        bigint references app.users(id),
  requires_proof     boolean not null default false,
  sent_back          boolean not null default false,
  start_date         date,
  duration_days      int,
  end_date           date,
  original_end_date  date,
  manual_dates       boolean not null default false,
  planned_start      date,
  planned_end        date,
  progress_pct       double precision not null default 0,
  pending_pct        double precision not null default 0,
  started_at         timestamptz,
  blocked_at         timestamptz,
  completed_at       timestamptz,
  created_by         bigint references app.users(id),
  created_at         timestamptz not null default now()
);
create index if not exists work_items_project_idx on app.work_items(project_id);
create index if not exists work_items_parent_idx on app.work_items(parent_id);
alter table app.work_items add column if not exists work_pct int not null default 0;

-- Every time someone moves a feature's percentage, with the note they gave.
create table if not exists app.progress_updates (
  id            bigint generated by default as identity primary key,
  work_item_id  bigint not null references app.work_items(id) on delete cascade,
  user_id       bigint not null references app.users(id),
  from_pct      int not null,
  to_pct        int not null,
  note          text not null,
  at            timestamptz not null default now()
);
create index if not exists progress_updates_item_idx on app.progress_updates(work_item_id, at);

create table if not exists app.assignments (
  id            bigint generated by default as identity primary key,
  work_item_id  bigint not null references app.work_items(id) on delete cascade,
  user_id       bigint not null references app.users(id),
  is_lead       boolean not null default false,
  assigned_by   bigint references app.users(id),
  assigned_at   timestamptz not null default now(),
  unique (work_item_id, user_id)
);
create index if not exists assignments_user_idx on app.assignments(user_id);

create table if not exists app.submissions (
  id            bigint generated by default as identity primary key,
  work_item_id  bigint not null references app.work_items(id) on delete cascade,
  submitted_by  bigint not null references app.users(id),
  note          text not null,
  submitted_at  timestamptz not null default now(),
  decision      text check (decision in ('approved','rejected')),
  decided_by    bigint references app.users(id),
  reason        text,
  decided_at    timestamptz
);
create index if not exists submissions_item_idx on app.submissions(work_item_id);

create table if not exists app.submission_files (
  id             bigint generated by default as identity primary key,
  submission_id  bigint not null references app.submissions(id) on delete cascade,
  kind           text not null check (kind in ('file','link')),
  url            text,
  file_name      text,
  stored_name    text,                 -- object path in the "submissions" storage bucket
  mime_type      text,
  size_bytes     bigint
);

create table if not exists app.daily_targets (
  id            bigint generated by default as identity primary key,
  user_id       bigint not null references app.users(id),
  date          date not null,
  work_item_id  bigint references app.work_items(id) on delete cascade,
  bucket        text not null,
  adhoc_title   text,
  created_by    bigint references app.users(id),
  created_at    timestamptz not null default now()
);
create index if not exists daily_targets_user_date_idx on app.daily_targets(user_id, date);

create table if not exists app.daily_logs (
  id             bigint generated by default as identity primary key,
  user_id        bigint not null references app.users(id),
  date           date not null,
  blockers       text,
  tomorrow_plan  text,
  submitted_at   timestamptz,
  updated_at     timestamptz not null default now(),
  unique (user_id, date)
);

create table if not exists app.log_entries (
  id            bigint generated by default as identity primary key,
  log_id        bigint not null references app.daily_logs(id) on delete cascade,
  target_id     bigint references app.daily_targets(id) on delete set null,
  work_item_id  bigint references app.work_items(id) on delete set null,
  category      text,
  work_done     text not null,
  hours         double precision not null default 0
);
create index if not exists log_entries_item_idx on app.log_entries(work_item_id);
create index if not exists log_entries_log_idx on app.log_entries(log_id);

create table if not exists app.flags (
  id               bigint generated by default as identity primary key,
  flag_key         text not null,          -- type:entity_type:entity_id, unique while open
  flag_type        text not null,
  severity         text not null check (severity in ('red','amber')),
  entity_type      text not null,
  entity_id        bigint not null,
  project_id       bigint,
  user_id          bigint,
  title            text not null,
  details          text,
  raised_at        timestamptz not null default now(),
  cleared_at       timestamptz,
  acknowledged_by  bigint references app.users(id),
  ack_note         text,
  acknowledged_at  timestamptz
);
create index if not exists flags_open_idx on app.flags(cleared_at, flag_key);

create table if not exists app.comments (
  id            bigint generated by default as identity primary key,
  work_item_id  bigint not null references app.work_items(id) on delete cascade,
  user_id       bigint not null references app.users(id),
  body          text not null,
  created_at    timestamptz not null default now()
);

create table if not exists app.notifications (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null references app.users(id),
  type        text not null,
  title       text not null,
  body        text,
  link        text,
  created_at  timestamptz not null default now(),
  read_at     timestamptz
);
create index if not exists notifications_user_idx on app.notifications(user_id, read_at);

create table if not exists app.audit_log (
  id          bigint generated by default as identity primary key,
  project_id  bigint,
  entity      text not null,
  entity_id   bigint,
  action      text not null,
  details     text,
  actor_id    bigint references app.users(id),
  at          timestamptz not null default now()
);
create index if not exists audit_log_project_idx on app.audit_log(project_id, at);

create table if not exists app.progress_snapshots (
  date          date not null,
  entity_type   text not null,
  entity_id     bigint not null,
  progress_pct  double precision not null,
  time_pct      double precision not null,
  primary key (date, entity_type, entity_id)
);

-- Lock every table: no direct access from the browser (defence in depth; the schema is private too).
do $$
declare t text;
begin
  foreach t in array array['settings','companies','holidays','users','projects','work_items','assignments','submissions',
    'submission_files','daily_targets','daily_logs','log_entries','flags','comments','notifications','audit_log','progress_snapshots','progress_updates']
  loop
    execute format('alter table app.%I enable row level security', t);
    execute format('revoke all on table app.%I from public, anon, authenticated', t);
  end loop;
end $$;

insert into app.settings (key, value) values
  ('default_weekly_offs', '0'),
  ('flag_review_days', '2'),
  ('flag_blocked_days', '2'),
  ('flag_stalled_days', '3'),
  ('flag_overload_count', '3'),
  ('flag_scope_growth_pct', '25'),
  ('min_note_chars', '30'),
  ('timezone', 'Asia/Kolkata')
on conflict (key) do nothing;
